# Generated by Django 2.0 on 2018-01-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(default='', max_length=5)),
                ('auth_name', models.CharField(max_length=10)),
                ('auth_id', models.IntegerField()),
                ('word', models.CharField(max_length=500)),
                ('avator', models.ImageField(upload_to='icons')),
                ('send_time', models.DateField()),
            ],
            options={
                'db_table': 'project_comment',
                'permissions': (('send_comment', '发表评论'),),
            },
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(default='', max_length=5)),
                ('file_name', models.CharField(max_length=50)),
                ('file_url', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'project_file',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('pro_title', models.TextField(max_length=50, verbose_name='项目内容')),
                ('pro_start', models.DateField(max_length=20, verbose_name='发布时间')),
                ('pro_end', models.DateField(max_length=20, verbose_name='截止时间')),
                ('pro_days', models.IntegerField(verbose_name='预计时间')),
                ('pro_type', models.CharField(max_length=10, verbose_name='项目类型')),
                ('pro_status', models.BooleanField(verbose_name='项目状态')),
                ('pro_auth_id', models.CharField(max_length=3, verbose_name='项目管理员')),
            ],
            options={
                'db_table': 'project',
                'permissions': (('assign_task', '分配任务'), ('up_file', '上传文件'), ('down_file', '下载文件')),
            },
        ),
        migrations.CreateModel(
            name='project_member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=5)),
                ('pro_member_id', models.IntegerField()),
            ],
            options={
                'db_table': 'project_member',
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(default='', max_length=5)),
                ('auth_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('order_time', models.DateField(verbose_name='预期时间')),
                ('true_date', models.DateField(verbose_name='实际完成时间')),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
    ]
