# Generated by Django 2.0 on 2017-12-29 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=10)),
                ('auth_id', models.IntegerField()),
                ('word', models.CharField(max_length=100)),
                ('avator', models.ImageField(upload_to='icons')),
                ('send_time', models.DateField()),
            ],
            options={
                'db_table': 'project_comment',
                'permissions': (('send_comment', '发表评论'),),
            },
        ),
        migrations.CreateModel(
            name='file',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=50)),
                ('file_url', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'project_file',
            },
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('pro_id', models.AutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=20, verbose_name='项目名称')),
                ('pro_title', models.TextField(max_length=50, verbose_name='项目内容')),
                ('pro_start', models.DateField(max_length=20, verbose_name='发布时间')),
                ('pro_end', models.DateField(max_length=20, verbose_name='截止时间')),
                ('pro_days', models.IntegerField(verbose_name='预计时间')),
                ('pro_type', models.CharField(max_length=10, verbose_name='项目类型')),
                ('pro_status', models.BooleanField(verbose_name='项目状态')),
                ('pro_auth_id', models.CharField(max_length=3, verbose_name='项目管理员')),
                ('pro_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.Comment')),
                ('pro_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.file')),
                ('pro_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project',
                'permissions': (('assign_task', '分配任务'), ('up_file', '上传文件'), ('down_file', '下载文件')),
            },
        ),
        migrations.CreateModel(
            name='task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('order_time', models.DateTimeField(verbose_name='预期时间')),
                ('date', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='pro_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myproject.task'),
        ),
    ]
