# Generated by Django 2.0 on 2017-12-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='order_time',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
