from django.urls import path
from admin import views

urlpatterns = [
    path('', views.admin, name='admin'),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('user_admin/', views.user_admin, name='user_admin'),
    path('forgetPwd/', views.ForgetPwd, name='ForgetPwd'),
    path('send_captch/', views.send_captch, name='send_captch'),
    path('get_captch/', views.get_captch, name='get_captch'),
    path('get_user/', views.get_user, name='get_user'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('edit_pwd/', views.edit_pwd, name='edit_pwd'),
    path('index/', views.admin_index, name="admin_index"),
    path('admin_login/', views.admin_login, name="admin_login"),
    path('save_user/',views.save_user,name='save_user'),
    path('add_user/',views.add_user,name='add_user'),
    path('manager/',views.manager,name='manager'),
    path('ordinary/',views.ordinary,name='ordinary'),
    path('PersonalTimeline/',views.PersonalTimeline,name='PersonalTimeline'),
    path('personal/',views.personal,name='personal'),
    path('personal_change/',views.personal_change,name='personal_change'),
    path('search/',views.search,name='search'),
    path('timeline/',views.timeline,name='timeline'),
    path('select/',views.select,name='select'),
    path('tableshows/',views.tableshows,name='tableshows'),
    path('get_trends/', views.get_trends, name='get_trends'),
    path('get_message/', views.get_message, name="get_message"),
    path('admin_messages', views.admin_messages, name="admin_messages"),
    path('admin_projects', views.admin_project, name="admin_project"),
    path('admin_project_detail/', views.admin_project_detail, name="admin_project_detail"),
    path('get_message_read/', views.get_message_read, name="get_message_read"),
    path('project_process/', views.project_process, name="project_process"),
    path('admin_create_project/', views.admin_create_project, name="admin_create_project"),
    path('admin_create_project/', views.admin_create_project, name="admin_create_project"),
]