# Generated by Django 2.0 on 2017-12-20 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=4, verbose_name='验证码')),
            ],
            options={
                'db_table': 'captch',
            },
        ),
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=5)),
                ('Monday', models.CharField(max_length=2)),
                ('Tuesday', models.CharField(max_length=2)),
                ('Wednesday', models.CharField(max_length=2)),
                ('Thursday', models.CharField(max_length=2)),
                ('Friday', models.CharField(max_length=2)),
                ('Saturday', models.CharField(max_length=2)),
                ('Sunday', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'time',
            },
        ),
    ]
