# Generated by Django 2.0 on 2017-12-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='time',
        ),
    ]
